Fitness1stMVCWeb/Controllers/CompendiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fitness1stMVCWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace Fitness1stMVCWeb.Controllers
{
    public class CompendiaController : Controller
    {
        private readonly CompendiumDbContext _context;

        public CompendiaController(CompendiumDbContext context)
        {
            _context = context;
        }

        // GET: Compendia
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Compendium.ToListAsync());
        }

        // GET: Compendia/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compendium = await _context.Compendium
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compendium == null)
            {
                return NotFound();
            }

            return View(compendium);
        }

        // GET: Compendia/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compendia/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryId,Category,Codes,METs,Description")] Compendium compendium)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compendium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compendium);
        }

        // GET: Compendia/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compendium = await _context.Compendium.FindAsync(id);
            if (compendium == null)
            {
                return NotFound();
            }
            return View(compendium);
        }

        // POST: Compendia/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryId,Category,Codes,METs,Description")] Compendium compendium)
        {
            if (id != compendium.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compendium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompendiumExists(compendium.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compendium);
        }

        // GET: Compendia/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compendium = await _context.Compendium
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compendium == null)
            {
                return NotFound();
            }

            return View(compendium);
        }

        // POST: Compendia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compendium = await _context.Compendium.FindAsync(id);
            _context.Compendium.Remove(compendium);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompendiumExists(int id)
        {
            return _context.Compendium.Any(e => e.Id == id);
        }
    }
}

Fitness1stMVCWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="" style="font-family:">@ViewData["Title"] - Fitness1st</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark navbar bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness1st</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Compendia" asp-action="Index">Compendium</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListUsers">Users</a>
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListRoles">Roles</a>
                                </div>
                            </li>
                        }
                    </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-success ">
        <div class="container">
            &copy; 2019 - Fitness1st - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>