Fitness1stMVCWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Fitness1stMVCWeb.Models;

namespace Fitness1stMVCWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fitness1stMVCWeb/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Fitness1stMVCWeb.Controllers
{
    public class InformationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fitness1stMVCWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@*This is the Page Heading and SubHeadings*@
    <div class="text-center ">
        <div class="container bg-secondary text-light text-center rounded shadow-lg p-3 border-secondary font-weight-bold">
            <h1 class="display-2 ">Welcome to Fitness1st</h1>
        </div>
        <div class="container">
            <div class="bg-success text-light p-2 rounded shadow table-responsive-md ">
                <h3 class="align-content-center text-lg-center">School Based Online Activity Log</h3>
                <br />
                <img src="../images/Activitybg1.png" alt="Physical Activity Pictures" class="img-fluid p-lg-3 shadow rounded-circle bg-dark" />
                <br />

            </div>
            @*Beginning of Informational Section Bottom*@
            <div class="container">
                @*Main Info Row*@
                <div class="row p-2 rounded shadow-lg">
                    <div class="col-sm rounded shadow bg-secondary p-2">
                        <div class="card rounded shadow border-success width: 18rem">
                            <img class="card-img-top bg-light img-thumbnail" src="../images/PELogPic2.jpg" alt="Card image cap">
                            <div class="card-title bg-success p-0 shadow-sm rounded-sm">
                                <h2> <a class="btn btn-success text-light font-weight-bold text-capitalize btn-outline-dark text-lg-center ">Journal Your Activity</a> </h2>
                            </div>
                            <div class="card-header bg-dark text-light p-0 rounded-sm shadow-sm">
                                <h3 class="text-md-center">
                                    Physical Activity Journals!
                                </h3>
                            </div>
                            <div class="card-text rounded-sm shadow-sm">
                                <div class="list-group bg-secondary">
                                    <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                    <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Meal Log</a>
                                    <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index" >Journaling FAQs</a>
                                    <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Learning About Your Data</a>
                                </div>
                                @*<div class="list-group bg-success">
                        <button type="button" class="list-group-item list-group-item-action bg-secondary text-light">
                            Cras justo odio
                        </button>
                        <button type="button" class="list-group-item list-group-item-action">Dapibus ac facilisis in</button>
                        <button type="button" class="list-group-item list-group-item-action">Morbi leo risus</button>
                        <button type="button" class="list-group-item list-group-item-action">Porta ac consectetur ac</button>
                        <button type="button" class="list-group-item list-group-item-action" disabled>Vestibulum at eros</button>
                    </div>*@
                            </div>
                            @*<div class="card-footer">
                    <a  class="btn btn-success box-shadow">Log Activity</a>
                </div>*@
                        </div>
                    </div>
                    @*______________________________________________________________________*@

                    @*Health Information*@
                    <div class="col-sm">
                        <div class="col-sm rounded shadow bg-secondary p-2">
                            <div class="card rounded shadow border-success width: 18rem">
                                <img class="card-img-top bg-light img-thumbnail" src="../images/Heart.png" alt="Card image cap">
                                <div class="card-title bg-success p-0 shadow-sm rounded-sm">
                                    <h2>Physical Activity and your Health</h2>
                                </div>
                                <div class="card-header bg-dark text-light p-0 rounded-sm shadow-sm">
                                    <h3>
                                        What impact does exercise have on health
                                    </h3>
                                </div>
                                <div class="card-text rounded-sm shadow-sm">
                                    <div class="list-group bg-secondary">
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light">Physical Effects</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Mental Health</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Spiritual Well Being</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Weight Management</a>
                                    </div>

                                    @*<div class="list-group bg-success">
                            <button type="button" class="list-group-item list-group-item-action bg-secondary text-light">
                                Cras justo odio
                            </button>
                            <button type="button" class="list-group-item list-group-item-action">Dapibus ac facilisis in</button>
                            <button type="button" class="list-group-item list-group-item-action">Morbi leo risus</button>
                            <button type="button" class="list-group-item list-group-item-action">Porta ac consectetur ac</button>
                            <button type="button" class="list-group-item list-group-item-action" disabled>Vestibulum at eros</button>
                        </div>*@
                                </div>
                                @*<div class="card-footer">
                        <a href="#" class="btn btn-success box-shadow">Log Activity</a>
                    </div>*@
                            </div>
                        </div>
                    </div>
                    @*______________________________________________________________________*@

                    @*Fitness Planning*@
                    <div class="col-sm">
                        <div class="col-sm rounded shadow bg-secondary p-2">
                            <div class="card rounded shadow border-success width: 18rem">
                                <img class="card-img-top bg-light img-thumbnail" src="../images/Planner.jpeg" alt="Card image cap">
                                <div class="card-title bg-success p-0 shadow-sm rounded-sm">
                                    <h2> Planning</h2>
                                </div>
                                <div class="card-header bg-dark text-light p-0 rounded-sm shadow-sm">
                                    <h3>
                                        "Proper Planning Prevents Poor Performance" <span class="font-italic"></span>
                                    </h3>
                                </div>
                                <div class="card-text rounded-sm shadow-sm">
                                    <div class="list-group bg-secondary">
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Your Plan</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Fitness Assessment</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Activity Planning</a>
                                        <a class="list-group-item list-group-item-action btn btn-success bg-success text-light" asp-area="" asp-controller="Information" asp-action="Index">Meal Planning</a>
                                    </div>
                                    @*<div class="list-group bg-success">
                            <button type="button" class="list-group-item list-group-item-action bg-secondary text-light">
                                Cras justo odio
                            </button>
                            <button type="button" class="list-group-item list-group-item-action">Dapibus ac facilisis in</button>
                            <button type="button" class="list-group-item list-group-item-action">Morbi leo risus</button>
                            <button type="button" class="list-group-item list-group-item-action">Porta ac consectetur ac</button>
                            <button type="button" class="list-group-item list-group-item-action" disabled>Vestibulum at eros</button>
                        </div>*@
                                </div>
                                @*<div class="card-footer">
                        <a href="#" class="btn btn-success box-shadow">Log Activity</a>
                    </div>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>